### ISSUE TITLE
Insert Assignment not inserting

### ISSUE THREAD

**Issue by REDitor** [REDitor/docker-template-phplatest#2]
the inserting of the new message through the form doesnt work. When I click on the submit button the hole page disappears except for the header. I followed the slides step by step so i'm not sure what i am doing wrong here. The following code can be found in branch Week2/In_Class_Exercise_2/Guestbook_Inserting_Data:
![image](https://user-images.githubusercontent.com/71357600/143683830-dff058fd-ba8a-488c-89bd-0cf9e58a9c01.png)

The yellow on the query is only because I didnt set up the connection in intelliJ.

**Comment by REDitor** [comment]
after clicking submit:
![image](https://user-images.githubusercontent.com/71357600/143683903-dbd93c4f-3689-4d1f-919b-f81e5adcfc9b.png)

**Comment by wimmelstein** [comment]
You are not completely following the slides. I would remove the action on the form. That way the current file is the action. Then insert that php code above your form, checking if it's a post or not. I have never seen php code in an action clause before...

**Comment by REDitor** [comment]
i did that because i couldnt make the script work in a seperate php file. Because on stackoverflow I saw everyone doign action="script.php", so the alternative for me was to put the whole script in there.

But I will give that a try thank you for responding so fast.

**Comment by REDitor** [comment]
Okay thank you sir it's working now. Its only not adding the new message to the page when I use:
echo "<meta http-equiv='refresh' content='0'>";
but thats not an issue just a little preference i had. I will close the issue thanks for the help
