### ISSUE TITLE
Week 4 Slides examples don't exist

### ISSUE THREAD

**Issue by REDitor** [REDitor/docker-template-phplatest#4]
Hi sir, 

I started the MVC assignments, but the links to the repo with the examples dont work. I checked it and I think the folders were removed.
I think I can figure it out but thought it might be helpful to let you know.

**Comment by wimmelstein** [comment]
You need to go to the root of the project. There you will find the examples.

**Comment by REDitor** [comment]
Yes thank you I found it. It's not in the repo listed in the slide though. It's in the inf2a repo. But thanks for the tip. I'll close the issue
